version: "3.9"
services:
  worker:
    image: rust:1.69
    volumes:
      - ".:/app"
    command:
      - /bin/sh
      - -c
      - |
        echo "Installing dependencies and starting worker..."
        apt-get update && \
          apt-get install -y libpq && \
          rm -rf /var/lib/apt/lists/*
        cd /app
        make dep
        cargo run
    environment:
      - REDIS_URL=redis://redis
      - DB_URL=postgresql://root:test@db:5432/test
      - QUEUE_URL=amqp://rabbitmq
      - WORKER_ID=1
    depends_on:
      - db
      - rabbitmq
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: "postgres:14.2-alpine"
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=test
     - POSTGRES_DB=test
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3.11-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
