[env]
IMAGE = "ghcr.io/combine-social/timeline-worker"
TAG = "latest"

[tasks.earthly]
script = ["brew install earthly", "earthly bootstrap"]

[tasks.libpq]
script = ["brew install libpq"]

[tasks.libpq.linux]
script = ["sudo apt-get install -y libpq-dev libpq5"]

[tasks.earthly.linux]
script = [
  "/bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'",
  "earthly bootstrap",
]

[tasks.dep]
dependencies = ["libpq", "earthly", "install-clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.lint_strict]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.test]
command = "cargo"
args = ["test", "--", "--test-threads", "1"]

[tasks.strip]
install_crate = "cargo-strip"
command = "cargo"
args = ["strip"]

[tasks.all]
dependencies = ["lint_strict", "test", "release", "strip"]

[tasks.image]
script = ["earthly +all --image=${IMAGE} --tag=${TAG}"]

[tasks.push]
dependencies = ["image"]
script = ["earthly --push +all --image=${IMAGE} --tag=${TAG}"]
