[package]
name = "worker"
version = "2.0.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
async-std = { version = "1.12.0", features = ["attributes"] }
