name: Lint and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          cargo make dep
      - name: Lint and test
        run: |
          cargo make lint_strict
          cargo make test
